### PR TITLE
Improve status code to string handling

### PR DESCRIPTION
**Pull request by jnooree**
Use `cuGetErrorString()` and `cublasGetStatusString()` for status code to string handling.

The latter require CUDA v11.4.2 (https://stackoverflow.com/a/72946225).

### CODE REVIEW

**Review by wilicc — APPROVED** [review]

**Comment by Rilomilo** [comment]
It's not work on Driver515.76 and cuda11.7, make throws an error:
```
gpu_burn-drv.cpp:82:27: error: 'cublasGetStatusString' was not declared in this scope
```

**Comment by jnooree** [comment]
Could you please share the full output of make? I can compile without errors.

```txt
g++ -O3 -Wno-unused-result -I/opt/cuda/11.7.0/include -c gpu_burn-drv.cpp
/opt/cuda/11.7.0/bin/nvcc -I/opt/cuda/11.7.0/include -arch=compute_50 -ptx compare.cu -o compare.ptx
gpu_burn-drv.cpp: In function ‘void showHelp()’:
gpu_burn-drv.cpp:748:47: warning: ' ' flag used with ‘%o’ gnu_printf format [-Wformat=]
  748 |         "  gpu-burn -m 50%% # burns using 50% of the available GPU memory\n");
      |                                               ^
gpu_burn-drv.cpp:748:47: warning: format ‘%o’ expects a matching ‘unsigned int’ argument [-Wformat=]
  748 |         "  gpu-burn -m 50%% # burns using 50% of the available GPU memory\n");
      |                                             ~~^
      |                                               |
      |                                               unsigned int
gpu_burn-drv.cpp: In function ‘int main(int, char**)’:
gpu_burn-drv.cpp:794:37: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
  794 |                 printf("ID %i: %s, %dMB\n", i_dev, device_name,
      |                                    ~^
      |                                     |
      |                                     int
      |                                    %ld
  795 |                        device_mem_l / 1000 / 1000);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            size_t {aka long unsigned int}
g++ -o gpu_burn gpu_burn-drv.o -O3 -L/opt/cuda/11.7.0/lib64/stubs -lcuda -L/opt/cuda/11.7.0/lib64 -L/opt/cuda/11.7.0/lib -Wl,-rpath=/opt/cuda/11.7.0/lib64 -Wl,-rpath=/opt/cuda/11.7.0/lib -lcublas -lcudart
```

**Comment by Rilomilo** [comment]
> Could you please share the full output of make? I can compile without errors.
> 
> This is the output from my make:
> 
> ```
> g++ -O3 -Wno-unused-result -I/opt/cuda/11.7.0/include -c gpu_burn-drv.cpp
> /opt/cuda/11.7.0/bin/nvcc -I/opt/cuda/11.7.0/include -arch=compute_50 -ptx compare.cu -o compare.ptx
> gpu_burn-drv.cpp: In function ‘void showHelp()’:
> gpu_burn-drv.cpp:748:47: warning: ' ' flag used with ‘%o’ gnu_printf format [-Wformat=]
>   748 |         "  gpu-burn -m 50%% # burns using 50% of the available GPU memory\n");
>       |                                               ^
> gpu_burn-drv.cpp:748:47: warning: format ‘%o’ expects a matching ‘unsigned int’ argument [-Wformat=]
>   748 |         "  gpu-burn -m 50%% # burns using 50% of the available GPU memory\n");
>       |                                             ~~^
>       |                                               |
>       |                                               unsigned int
> gpu_burn-drv.cpp: In function ‘int main(int, char**)’:
> gpu_burn-drv.cpp:794:37: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
>   794 |                 printf("ID %i: %s, %dMB\n", i_dev, device_name,
>       |                                    ~^
>       |                                     |
>       |                                     int
>       |                                    %ld
>   795 |                        device_mem_l / 1000 / 1000);
>       |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                            |
>       |                                            size_t {aka long unsigned int}
> g++ -o gpu_burn gpu_burn-drv.o -O3 -L/opt/cuda/11.7.0/lib64/stubs -lcuda -L/opt/cuda/11.7.0/lib64 -L/opt/cuda/11.7.0/lib -Wl,-rpath=/opt/cuda/11.7.0/lib64 -Wl,-rpath=/opt/cuda/11.7.0/lib -lcublas -lcudart
> ```

while my make output is like this:
```
~/gpu-burn-master# make
g++  -O3 -Wno-unused-result -I/usr/local/cuda/include -c gpu_burn-drv.cpp
gpu_burn-drv.cpp: In function 'void _checkError(cublasStatus_t, std::string, int, std::string)':
gpu_burn-drv.cpp:82:27: error: 'cublasGetStatusString' was not declared in this scope
   82 |         const char *err = cublasGetStatusString(rCode);
      |                           ^~~~~~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp: In function 'void showHelp()':
gpu_burn-drv.cpp:748:47: warning: ' ' flag used with '%o' gnu_printf format [-Wformat=]
  748 |         "  gpu-burn -m 50%% # burns using 50% of the available GPU memory\n");
      |                                               ^
gpu_burn-drv.cpp:748:47: warning: format '%o' expects a matching 'unsigned int' argument [-Wformat=]
  748 |         "  gpu-burn -m 50%% # burns using 50% of the available GPU memory\n");
      |                                             ~~^
      |                                               |
      |                                               unsigned int
gpu_burn-drv.cpp: In function 'int main(int, char**)':
gpu_burn-drv.cpp:794:37: warning: format '%d' expects argument of type 'int', but argument 4 has type 'size_t' {aka 'long unsigned int'} [-Wformat=]
  794 |                 printf("ID %i: %s, %dMB\n", i_dev, device_name,
      |                                    ~^
      |                                     |
      |                                     int
      |                                    %ld
  795 |                        device_mem_l / 1000 / 1000);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            size_t {aka long unsigned int}
make: *** [Makefile:36: gpu_burn-drv.o] Error 1
```

**Comment by jnooree** [comment]
What is the output of `/usr/local/cuda/bin/nvcc --version`?

**Comment by Rilomilo** [comment]
nvcc shows this:
```
~# /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```
I figured it out, nvidia-smi shows me "CUDA Version: 11.7 ", while it doesn't mean I have installed cuda11.7 and only means my driver supports cuda up to version 11.7. Thanks for your help: ) I think it's kind to add nvcc requirement into readme.md for those who does't familiar with nvcc compile like me.

**Comment by llk2why** [comment]
> It's not work on Driver515.76 and cuda11.7, make throws an error:
> 
> ```
> gpu_burn-drv.cpp:82:27: error: 'cublasGetStatusString' was not declared in this scope
> ```

met same problem, it results from [this commit](https://github.com/wilicc/gpu-burn/commit/564a9a6d4e953d668bf7584a9c575679d861b1a7#comments). It's not a good idea to degrade compatility just for using the new simple API.
